- src/pages/Devtools/ConsolePanel/components/ConsoleNode/index.tsx
- src/pages/Devtools/NetworkPanel/comps.tsx
- src/pages/Devtools/NetworkPanel/index.tsx
- src/pages/Devtools/TypeNode/index.tsx
- src/pages/Devtools/index.tsx
> fix: remove 'classnames' import statment 

- .github/workflows/release.yml
- .gitignore
- README.md
- README_CN.md
- backend/build.sh
- backend/publish/install.js
- backend/publish/page-spy-api.js
- backend/publish/page-spy.js
- package.json
- yarn.lock
add node package publish and run server with node package
> add node package publish and run server with node package

- src/pages/Devtools/ConsolePanel/components/Timestamp/index.less
- src/pages/Devtools/ConsolePanel/components/Timestamp/index.tsx
- src/pages/Devtools/ConsolePanel/index.tsx
> feature: 日志台时间显示

- backend/build.sh
ref: https://github.com/golang/go/issues/57328
> Fix incompatible in low version glibc

- src/pages/Devtools/ConsolePanel/components/ErrorDetailDrawer/index.less
- src/store/socket-message/utils.ts
- src/utils/parseError.ts
> optimize error source code location

- package.json
- src/assets/image/cookie.svg
- src/assets/image/database.svg
- src/assets/image/storage.svg
- src/assets/locales/en.json
- src/assets/locales/ja.json
- src/assets/locales/ko.json
- src/assets/locales/zh.json
- src/pages/Devtools/ConnectStatus/index.tsx
- src/pages/Devtools/PagePanel/index.tsx
- src/pages/Devtools/StoragePanel/TableContent/index.less
- src/pages/Devtools/StoragePanel/TableContent/index.tsx
- src/pages/Devtools/StoragePanel/index.tsx
- src/pages/Devtools/index.tsx
- src/store/cache-detail/index.ts
- src/store/socket-message/index.ts
- src/store/socket-message/message-type.ts
- src/store/socket-message/socket.ts
- src/types/env.d.ts
- src/utils/useEventListener.ts
- yarn.lock
> feat: support IndexedDB

- src/assets/locales/zh.json
> fix: storage translate error

- package.json
- src/store/socket-message/index.ts
- yarn.lock
Close https://github.com/HuolalaTech/page-spy-web/issues/88
> fix: sync storage data which name is conflict with prototype method name

- src/assets/locales/en.json
- src/assets/locales/ja.json
- src/assets/locales/ko.json
- src/assets/locales/zh.json
- src/pages/Devtools/ConsolePanel/components/FooterInput/index.tsx
- src/pages/Devtools/ConsolePanel/components/MainContent/index.tsx
- src/store/misc/index.ts
> feat: Auto-scroll

- .gitignore
- src/components/SelectRoom/index.tsx
- src/pages/Devtools/BrowserFrame/index.tsx
- src/pages/Devtools/index.tsx
- src/pages/RoomList/index.tsx
https://github.com/HuolalaTech/page-spy-web/discussions/115
> feat: remove version query

- README.md
- README_JA.md
- README_ZH.md
I created Japanese translated README.
> doc: add Japanese readme

- CONTRIBUTING.md
- CONTRIBUTING_JA.md
- CONTRIBUTING_ZH.md
> doc: add Japanese contributing.md

- package.json
- src/apis/index.ts
- src/assets/image/lock.svg
- src/assets/locales/en.json
- src/assets/locales/ja.json
- src/assets/locales/ko.json
- src/assets/locales/zh.json
- src/pages/Devtools/index.tsx
- src/pages/RoomList/DebugButton/SecretModal.tsx
- src/pages/RoomList/DebugButton/index.tsx
- src/pages/RoomList/RoomCard/index.tsx
- src/pages/RoomList/index.tsx
- src/store/socket-message/index.ts
- src/types/api.d.ts
- yarn.lock
https://github.com/HuolalaTech/page-spy/pull/78
1. 如果房间需要密码，点击按钮后会要求输入客户端生成的密码；
2. 优化房间列表展示：有效房间按「createdAt」升序、失效房间按「activeAt」降序；
> add necessary authorization before open devtools

- package.json
- src/pages/Replay/PlayControl/components/Actions.tsx
- src/pages/Replay/PlayControl/components/CurrentTime.tsx
- src/pages/Replay/PlayControl/components/Duration.tsx
- src/pages/Replay/PlayControl/components/ProgressBar.tsx
- src/pages/Replay/PlayControl/index.less
- src/pages/Replay/PlayControl/index.tsx
- src/pages/Replay/PluginPanel/components/ConsolePanel/index.tsx
- src/pages/Replay/PluginPanel/components/NetworkPanel/index.tsx
- src/pages/Replay/RRWebPlayer/index.tsx
- src/pages/Replay/index.tsx
- src/store/replay.ts
- yarn.lock
> Refactor `<Replay />` to fix page-spy-web#186

- src/pages/Devtools/ElementPanel/index.tsx
- src/pages/Devtools/ElementPanel/utils.ts
- src/pages/Devtools/PagePanel/index.tsx
- src/store/socket-message/utils.ts
> fix: html tag attributes lost

- src/components/NetworkTable/NetworkDetail/index.tsx
- src/components/NetworkTable/ResponseBody/index.tsx
- src/components/NetworkTable/index.less
- src/components/NetworkTable/index.tsx
- src/components/NetworkTable/utils.ts
- src/pages/Replay/PlayControl/index.tsx
- src/pages/Replay/PluginPanel/components/ConsolePanel/index.tsx
- src/pages/Replay/PluginPanel/components/NetworkPanel/index.tsx
- src/pages/Replay/PluginPanel/components/StoragePanel/StorageContent.tsx
- src/store/replay.ts
- src/store/socket-message/index.ts
1. 支持展示 EventSource 的数据 fix #202 ；
2. 优化 Network 详情面板布局 fix #183 ；
fix #202 #183
> feat: add `EventStream` in Network panel

- src/store/socket-message/index.ts
修复uniapp 编译为 app 时 network 不显示 Name
#220
> fix network name empty in uniapp to native

- src/components/NetworkTable/index.tsx
- src/store/socket-message/index.ts
- src/store/socket-message/utils.ts
- src/utils/index.ts
related: https://github.com/HuolalaTech/page-spy/pull/102
> update network data in socket-store because sdk remove resolveUrlInfo

- src/components/NetworkTable/index.less
- src/store/replay.ts
https://github.com/HuolalaTech/page-spy/pull/105
> show whole lifecycle for network request when replay

- src/pages/Devtools/NetworkPanel/index.less
- src/pages/Devtools/NetworkPanel/index.tsx
feature: [#261 ](https://github.com/HuolalaTech/page-spy-web/issues/261)
> feat: add filter options for network requests

- .github/workflows/build_docker.yml
- .github/workflows/build_docker_hub.yml
- .github/workflows/release_docker_hub.yml
- .github/workflows/version_docker_hub.yml
> add push docker hub spport

- src/components/NetworkTable/NetworkDetail/index.tsx
- src/components/NetworkTable/RequestPayloadBlock/index.tsx
Fix https://github.com/HuolalaTech/page-spy-web/issues/267
> Optimize the network payload if meet the application/x-www-form-urlencoded

- src/App.tsx
- src/assets/locales/en.json
- src/assets/locales/ja.json
- src/assets/locales/ko.json
- src/assets/locales/zh.json
- src/components/SystemContent/index.less
- src/pages/Docs/md/data-harbor.en.mdx
- src/pages/Docs/md/data-harbor.zh.mdx
- src/pages/Docs/md/pagespy.en.mdx
- src/pages/Docs/md/pagespy.zh.mdx
- src/pages/LogList/index.tsx
- src/pages/Replay/Meta/index.less
- src/pages/Replay/Meta/index.tsx
- src/pages/Replay/PlayControl/components/Actions.tsx
- src/pages/Replay/PlayControl/components/ProgressBar.tsx
- src/pages/Replay/RRWebPlayer/index.tsx
- src/pages/Replay/index.less
- src/pages/Replay/index.tsx
- src/store/replay.ts
- src/utils/brand.ts
> feat: replay support periods log

- src/components/ConsoleNode/ErrorTrace/index.tsx
- src/components/ErrorDetailDrawer/index.less
- src/components/ErrorDetailDrawer/index.tsx
- src/components/Timestamp/index.less
- src/utils/parseError.ts
format error message and support locate source code which is not in js
> Optimize error locate

- index.html
- src/App.tsx
- src/components/DropFile/index.less
- src/components/DropFile/index.tsx
- src/pages/OSpy/components/Replayer/index.tsx
- src/pages/OSpy/index.tsx
> fix cannot replay by url and support drop file to replay globally

- src/pages/MainDocs/md/server-configuration.en.mdx
- src/pages/MainDocs/md/server-configuration.ja.mdx
- src/pages/MainDocs/md/server-configuration.ko.mdx
- src/pages/MainDocs/md/server-configuration.zh.mdx
1. add doc for selfRpcAddress
2. add more explanation & examples for newly added config
> feat(doc): add doc for selfRpcAddress
